hide_cursor_when_typing: true

background_opacity: 0.95

font:
  normal:
    family: SauceCodePro Nerd Font Mono
    style: Regular

  bold:
    family: SauceCodePro Nerd Font Mono
    style: Bold

  italic:
    family: SauceCodePro Nerd Font Mono
    style: Italic

  size: 12.0

  offset:
    y: 1

colors:
  primary:
    # background: '0x1e2127'
    background: '0x0e1117'
    foreground: '0xabb2bf'

  normal:
    black:   '0x1e2127'
    red:     '0xe06c75'
    green:   '0x98c379'
    yellow:  '0xd19a66'
    blue:    '0x61afef'
    magenta: '0xc678dd'
    cyan:    '0x56b6c2'
    white:   '0x828791'

  bright:
    black:   '0x5c6370'
    red:     '0xe06c75'
    green:   '0x98c379'
    yellow:  '0xd19a66'
    blue:    '0x61afef'
    magenta: '0xc678dd'
    cyan:    '0x56b6c2'
    white:   '0xe6efff'

  dim:
    black:   '0x1e2127'
    red:     '0xe06c75'
    green:   '0x98c379'
    yellow:  '0xd19a66'
    blue:    '0x61afef'
    magenta: '0xc678dd'
    cyan:    '0x56b6c2'
    white:   '0x828791'
